version: '3.8'

services:
  # Serviço de aplicação PHP
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: sgo_app
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
      - redis
    environment:
      - APP_ENV=local
      - DB_HOST=db
      - DB_PORT=5432
      - DB_CONNECTION=pgsql
      - DB_DATABASE=sgo
      - DB_USERNAME=felicio
      - DB_PASSWORD=123456
      - REDIS_HOST=redis
    networks:
      - sgo_network

  # Serviço de banco de dados PostgreSQL  
  db:
    image: postgres:15-alpine
    container_name: sgo_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sgo
      - POSTGRES_USER=felicio
      - POSTGRES_PASSWORD=123456
    networks:
      - sgo_network

  # Serviço Redis para cache e sessões
  redis:
    image: redis:alpine
    container_name: sgo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sgo_network

  # Opcional: Pgadmin para gerenciamento do banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: sgo_pgadmin
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@sgo.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - db
    networks:
      - sgo_network

volumes:
  postgres_data:
  redis_data:

networks:
  sgo_network:
    driver: bridge